---
- name: Upgrade all Ubuntu VMs
  hosts: all
  become: true
  become_user: root
  
  tasks:
  - name: Update apt package cache and upgrade all packages
    ansible.builtin.apt:
      name: "*"
      update_cache: yes
      state:  latest
