---
- name: Upgrade all Ubuntu VMs
  hosts: hetzner

  tasks:
  - name: Update apt package cache and upgrade all packages
    ansible.builtin.apt:
      name: "*"
      update_cache: yes
      state:  latest
