---
- name: Update Mailcow
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Ensure Mailcow directory exists
      file:
        path: /opt/mailcow-dockerized
        state: directory

    - name: Change to Mailcow directory
      command: chdir=/opt/mailcow-dockerized

    - name: Run update.sh script
      command: ./update.sh
      args:
        chdir: /opt/mailcow-dockerized

    - name: Cleanup Docker system
      command: docker system prune -f
      ignore_errors: yes
