---
- name: Update Mailcow
  hosts: all
  become: yes
  tasks:
    - name: Change to Mailcow directory
      command: cd /opt/mailcow-dockerized

    - name: Run update.sh script
      command: ./update.sh

    - name: Cleanup Docker system
      command: docker system prune -f
      ignore_errors: yes
